
package gui;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import factory.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import modelo.usuario;


public class Usuario_Gui extends javax.swing.JFrame {
   private Connection con;
   
   
    public Usuario_Gui() {
        // Instantiate ConnectionFactory and establish a connection
        ConnectionFactory cf = new ConnectionFactory();
        con = cf.getConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idade_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        aldeia_txt = new javax.swing.JTextField();
        status_txt = new javax.swing.JTextField();
        obs_txt = new javax.swing.JTextField();
        blood_txt = new javax.swing.JTextField();
        nome_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        win_txt = new javax.swing.JTextField();
        error_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_limpa = new javax.swing.JButton();
        btn_adiciona = new javax.swing.JButton();
        btn_atualiza = new javax.swing.JButton();
        btn_deleta = new javax.swing.JButton();
        btn_seleciona = new javax.swing.JButton();
        btn_especial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        des_txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("ID");

        jLabel2.setText("Nome");

        jLabel3.setText("Idade");

        jLabel4.setText("Aldeia");

        jLabel5.setText("Status");

        jLabel6.setText("Observacao");

        jLabel7.setText("Blood");

        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });

        jLabel8.setText("WIN");

        jLabel9.setText("ERROR");

        jLabel10.setText("Descricao");

        btn_limpa.setText("LIMPAR");
        btn_limpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpaActionPerformed(evt);
            }
        });

        btn_adiciona.setText("ADICIONAR");
        btn_adiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionaActionPerformed(evt);
            }
        });

        btn_atualiza.setText("ATUALIZAR");
        btn_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizaActionPerformed(evt);
            }
        });

        btn_deleta.setText("DELETAR");
        btn_deleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletaActionPerformed(evt);
            }
        });

        btn_seleciona.setText("SELECIONAR");
        btn_seleciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionaActionPerformed(evt);
            }
        });

        btn_especial.setText("SELECIONAR ESPECIAL");
        btn_especial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_especialActionPerformed(evt);
            }
        });

        des_txt.setColumns(20);
        des_txt.setRows(5);
        jScrollPane1.setViewportView(des_txt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blood_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obs_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aldeia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_deleta)
                    .addComponent(btn_limpa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_seleciona)
                        .addGap(38, 38, 38)
                        .addComponent(btn_especial)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(error_txt))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(win_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(72, 72, 72))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(158, 158, 158))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_adiciona)
                                    .addGap(74, 74, 74)
                                    .addComponent(btn_atualiza)))
                            .addGap(90, 90, 90)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(win_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1))
                            .addComponent(id_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(error_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aldeia_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btn_limpa)
                    .addComponent(btn_adiciona)
                    .addComponent(btn_atualiza))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obs_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btn_deleta)
                    .addComponent(btn_seleciona)
                    .addComponent(btn_especial))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blood_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_txtActionPerformed

    private void btn_limpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpaActionPerformed
       nome_txt.setText("");
       idade_txt.setText("");
       aldeia_txt.setText("");
       status_txt.setText("");
       obs_txt.setText("");
       blood_txt.setText("");
       win_txt.setText("");
       error_txt.setText("");
       des_txt.setText("");
       
    }//GEN-LAST:event_btn_limpaActionPerformed

    private void btn_selecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionaActionPerformed
            try {
   
    String query = "SELECT * from personagens WHERE id = ?";
    PreparedStatement psmt = con.prepareStatement(query);
    psmt.setInt(1, Integer.parseInt(id_txt.getText()));
    
    ResultSet rs = psmt.executeQuery();

    while (rs.next()) {
        String nome = rs.getString("nome");
        nome_txt.setText(nome);
        String idade = rs.getString("idade");
        idade_txt.setText(idade);
        String aldeia = rs.getString("aldeia");
        aldeia_txt.setText(aldeia);
        String status = rs.getString("status");
        status_txt.setText(status);
        String obs = rs.getString("observacao");
        obs_txt.setText(obs);
        String blood = rs.getString("blood");
        obs_txt.setText(blood);
        
    }

} catch (SQLException ex) {
    ex.printStackTrace();
}
    }//GEN-LAST:event_btn_selecionaActionPerformed

    private void btn_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizaActionPerformed
      try { String update = "UPDATE personagens SET nome= ? WHERE id = ?";
             String update1 = "UPDATE personagens SET idade= ? WHERE id = ?";
             String update2 = "UPDATE personagens SET aldeia = ? WHERE id = ?";
             String update3 = "UPDATE personagens SET status= ? WHERE id = ?";
             String update4 = "UPDATE personagens SET observacao = ? WHERE id = ?";
             String update5 = "UPDATE personagens SET blood = ? WHERE id = ?";
             

             PreparedStatement psmt = con.prepareStatement(update);
             psmt.setString(1, nome_txt.getText().isEmpty() ? null : nome_txt.getText());
             psmt.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             int rowsAffected = psmt.executeUpdate();

             PreparedStatement psmt1 = con.prepareStatement(update1);
             psmt1.setString(1, idade_txt.getText().isEmpty() ? null : idade_txt.getText());
             psmt1.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt1.executeLargeUpdate();

             PreparedStatement psmt2 = con.prepareStatement(update2);
             psmt2.setString(1, aldeia_txt.getText().isEmpty() ? null : aldeia_txt.getText());
             psmt2.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt2.executeUpdate();

             PreparedStatement psmt3 = con.prepareStatement(update3);
             psmt3.setString(1, status_txt.getText().isEmpty() ? null : status_txt.getText());
             psmt3.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt3.executeUpdate();
            
             PreparedStatement psmt4 = con.prepareStatement(update4);
             psmt4.setString(1, obs_txt.getText().isEmpty() ? null : obs_txt.getText());
             psmt4.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt4.executeUpdate();
             
             PreparedStatement psmt5 = con.prepareStatement(update5);
             psmt5.setString(1, blood_txt.getText().isEmpty() ? null : blood_txt.getText());
             psmt5.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt5.executeUpdate();
             
             
             String mensagem = rowsAffected > 0 ? "Sucesso" : "Erro";
             win_txt.setText(mensagem);
             error_txt.setText(mensagem);
             
             } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_atualizaActionPerformed

    private void btn_adicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionaActionPerformed
       try {
        String insert = "INSERT INTO personagens(nome, idade, aldeia, status, observacao, blood) VALUES (?,?,?,?,?,?)";
       PreparedStatement psmt = con.prepareStatement(insert);
       
       psmt.setString(1, nome_txt.getText());
       psmt.setInt(2, Integer.parseInt(idade_txt.getText()));
       psmt.setString(3, aldeia_txt.getText());
       psmt.setString(4, status_txt.getText());
       psmt.setString(5, obs_txt.getText());
        psmt.setString(6, blood_txt.getText());
       
       int rowsAffected = psmt.executeUpdate();
       if(rowsAffected ==1 ){
           win_txt.setText("Sucesso");
       }
       else {
           error_txt.setText("Erro!");
       }
       } catch (SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
         
    }//GEN-LAST:event_btn_adicionaActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void btn_deletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletaActionPerformed
       try { String delete = "DELETE FROM personagens WHERE id= ?";
        PreparedStatement psmt = con.prepareStatement(delete);
        psmt.setInt(1, Integer.parseInt(id_txt.getText()));
        
        int rowsAffected = psmt.executeUpdate();
             String mensagem = rowsAffected > 0 ? "Sucesso" : "Erro";
             win_txt.setText(mensagem);
             error_txt.setText(mensagem);
                
       } catch (SQLException e) {
           
       }
           
    }//GEN-LAST:event_btn_deletaActionPerformed

    private void btn_especialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_especialActionPerformed

        try {
        String query = "SELECT relacao.id_personagem, relacao.descricao, personagens.nome FROM relacao INNER JOIN personagens ON personagens.id = relacao.id_personagem";
        PreparedStatement psmt = con.prepareStatement(query);
        ResultSet rs = psmt.executeQuery();
        while (rs.next()) {
            int id = rs.getInt("id_personagem");
           id_txt.setText(Integer.toString(id));
            String nome = rs.getString("nome");
            nome_txt.setText(nome);
            String descricao = rs.getString("descricao");
            des_txt.setText(descricao);
            
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }//GEN-LAST:event_btn_especialActionPerformed
    }
    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aldeia_txt;
    private javax.swing.JTextField blood_txt;
    private javax.swing.JButton btn_adiciona;
    private javax.swing.JButton btn_atualiza;
    private javax.swing.JButton btn_deleta;
    private javax.swing.JButton btn_especial;
    private javax.swing.JButton btn_limpa;
    private javax.swing.JButton btn_seleciona;
    private javax.swing.JTextArea des_txt;
    private javax.swing.JTextField error_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JTextField idade_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome_txt;
    private javax.swing.JTextField obs_txt;
    private javax.swing.JTextField status_txt;
    private javax.swing.JTextField win_txt;
    // End of variables declaration//GEN-END:variables
}
