
package outro_form;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author CAMARGO
 */
public class aula09 extends javax.swing.JFrame {
    static Connection con;
         static {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/naruto_the_anime?zeroDateTimeBehavior=CONVERT_TO_NULL ";
            String user = "root";
            String password = "";
            con = DriverManager.getConnection(url, user, password);
           
        } catch (ClassNotFoundException ex) {
            System.err.println("Unable to load JDBC driver");
            ex.printStackTrace();
        } catch (SQLException ex) {
            System.err.println("Unable to connect to database");
            ex.printStackTrace();
        }
    }
   
    public aula09() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        idade_txt = new javax.swing.JTextField();
        aldeia_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        status_txt = new javax.swing.JTextField();
        btn_limpar = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_consulta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campo_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        obs_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("ID");

        jLabel2.setText("nome");

        jLabel3.setText("idade");

        jLabel4.setText("aldeia");

        jLabel5.setText("status");

        btn_limpar.setLabel("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_add.setLabel("Adicionat");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_editar.setLabel("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_consulta.setLabel("Consulta");
        btn_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaActionPerformed(evt);
            }
        });

        jLabel6.setText("Campo");

        jLabel7.setText("observacao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_editar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nome_txt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idade_txt)
                                        .addComponent(aldeia_txt)
                                        .addComponent(status_txt)
                                        .addComponent(obs_txt)))))
                        .addGap(57, 57, 57)
                        .addComponent(btn_limpar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_add)
                            .addComponent(btn_consulta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(campo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(244, 244, 244))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(campo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aldeia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(status_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(obs_txt))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_limpar)
                            .addComponent(btn_add))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_editar)
                            .addComponent(btn_consulta))))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       try {
        String insert = "INSERT INTO personagens(nome, idade, aldeia, status, observacao) VALUES (?,?,?,?,?)";
       PreparedStatement psmt = con.prepareStatement(insert);
       
       psmt.setString(1, nome_txt.getText());
       psmt.setInt(2, Integer.parseInt(idade_txt.getText()));
       psmt.setString(3, aldeia_txt.getText());
       psmt.setString(4, status_txt.getText());
       psmt.setString(5, obs_txt.getText());
       
       int rowsAffected = psmt.executeUpdate();
       if(rowsAffected ==1 ){
           campo_txt.setText("Sucesso");
       }
       else {
           campo_txt.setText("Erro!");
       }
       } catch (SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
      id_txt.setText("");
        nome_txt.setText("");
       idade_txt.setText("");
       aldeia_txt.setText("");
       status_txt.setText("");
       obs_txt.setText("");
       campo_txt.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
       try {
             String update = "UPDATE personagens SET nome= ? WHERE id = ?";
              String update1 = "UPDATE personagens SET idade= ? WHERE id = ?";
             String update2 = "UPDATE personagens SET aldeia= ? WHERE id = ?";
             String update3 = "UPDATE personagens SET status= ? WHERE id = ?";
             String update4 = "UPDATE personagens SET observacao = ? WHERE id = ?";

             PreparedStatement psmt = con.prepareStatement(update);
             psmt.setString(1, nome_txt.getText().isEmpty() ? null : nome_txt.getText());
             psmt.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             int rowsAffected = psmt.executeUpdate();
             
             PreparedStatement psmt1 = con.prepareStatement(update1);
             psmt1.setInt(1, idade_txt.getText().isEmpty() ? 0 : Integer.parseInt(idade_txt.getText()));
             psmt1.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt1.executeLargeUpdate();

             PreparedStatement psmt2 = con.prepareStatement(update2);
             psmt2.setString(1, aldeia_txt.getText().isEmpty() ? null : aldeia_txt.getText());
             psmt2.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt2.executeLargeUpdate();

             PreparedStatement psmt3 = con.prepareStatement(update3);
             psmt3.setString(1, status_txt.getText().isEmpty() ? null : status_txt.getText());
             psmt3.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt3.executeUpdate();

             PreparedStatement psmt4 = con.prepareStatement(update4);
             psmt4.setString(1, obs_txt.getText().isEmpty() ? null : obs_txt.getText());
             psmt4.setInt(2, id_txt.getText().isEmpty() ? 0 : Integer.parseInt(id_txt.getText()));
             rowsAffected += psmt4.executeUpdate();
             
             String mensagem = rowsAffected > 0 ? "Sucesso" : "Erro";
             campo_txt.setText(mensagem);
             } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaActionPerformed
        try {
   
    String query = "SELECT * from personagens WHERE id = ?";
    PreparedStatement psmt = con.prepareStatement(query);
    psmt.setInt(1, Integer.parseInt(id_txt.getText()));
    
    ResultSet rs = psmt.executeQuery();

    while (rs.next()) {
        String nome = rs.getString("nome");
        nome_txt.setText(nome);
        String idade = rs.getString("idade");
        idade_txt.setText(idade);
        String aldeia = rs.getString("aldeia");
        aldeia_txt.setText(aldeia);
        String status = rs.getString("status");
        status_txt.setText(status);
        String obs = rs.getString("observacao");
        obs_txt.setText(obs);
        
    }

} catch (SQLException ex) {
    ex.printStackTrace();
}
    }//GEN-LAST:event_btn_consultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aula09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aula09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aula09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aula09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aula09().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aldeia_txt;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_consulta;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JTextField campo_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JTextField idade_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_txt;
    private javax.swing.JTextField obs_txt;
    private javax.swing.JTextField status_txt;
    // End of variables declaration//GEN-END:variables
}
